# Regenerates src/Protocol/constants_generated.jl from the MySQL server's public headers.
#
# Only numeric enum/define *values* are extracted (facts, not expression). Run:
#
#     julia scripts/gen_constants.jl [path/to/my_command.h path/to/mysql_com.h path/to/field_types.h]
#
# Without arguments the headers are downloaded from the mysql-server trunk. The generated
# file records the source URLs and SHA-256 of the inputs so cross-checks are reproducible.

using SHA, Downloads

const MY_COMMAND_URL = "https://raw.githubusercontent.com/mysql/mysql-server/trunk/include/my_command.h"
const MYSQL_COM_URL = "https://raw.githubusercontent.com/mysql/mysql-server/trunk/include/mysql_com.h"
const FIELD_TYPES_URL = "https://raw.githubusercontent.com/mysql/mysql-server/trunk/include/field_types.h"

function fetch_header(url::String, path::Union{Nothing, String})
    path !== nothing && return read(path, String)
    return String(take!(Downloads.download(url, IOBuffer())))
end

function strip_comments(src::String)
    src = replace(src, r"/\*.*?\*/"s => " ")
    return replace(src, r"//[^\n]*" => "")
end

function parse_value(expr::String)
    e = strip(expr)
    m = match(r"^\(?\s*1UL?\s*<<\s*(\d+)\s*\)?$", e)
    m !== nothing && return UInt64(1) << parse(Int, m.captures[1])
    m = match(r"^\(?\s*(0x[0-9A-Fa-f]+|\d+)\s*L?\)?$", e)
    m !== nothing && return parse(UInt64, m.captures[1])
    return nothing
end

# Parses `enum NAME { A, B = 3, ... };` into an ordered Vector{Pair{String,UInt64}}.
function parse_enum(src::String, name::String)
    m = match(Regex("enum\\s+$name\\s*(?::\\s*\\w+)?\\s*\\{(.*?)\\};", "s"), src)
    m === nothing && error("enum $name not found")
    pairs = Pair{String, UInt64}[]
    next = UInt64(0)
    for item in split(m.captures[1], ',')
        item = strip(item)
        isempty(item) && continue
        parts = split(item, '=')
        key = strip(parts[1])
        occursin(r"^[A-Z_][A-Z0-9_]*$", key) || continue
        value = length(parts) == 2 ? parse_value(String(parts[2])) : next
        value === nothing && error("cannot parse enum value for $key: $item")
        push!(pairs, key => value)
        next = value + 1
    end
    return pairs
end

# Parses `#define NAME value` (with line continuations) for names matching `pattern`.
function parse_defines(src::String, pattern::Regex)
    joined = replace(src, r"\\\r?\n" => " ")
    pairs = Pair{String, UInt64}[]
    for m in eachmatch(r"#define\s+([A-Z_][A-Z0-9_]*)\s+([^\n]+)", joined)
        name = String(m.captures[1])
        occursin(pattern, name) || continue
        value = parse_value(String(m.captures[2]))
        value === nothing && continue
        push!(pairs, name => value)
    end
    return pairs
end

function emit_group(io::IO, title::String, pairs::Vector{Pair{String, UInt64}}, T::String)
    println(io, "# ", title)
    for (name, value) in pairs
        println(io, "const ", name, " = ", T, "(", value, ")")
    end
    println(io)
    return nothing
end

function main(args)
    my_command = fetch_header(MY_COMMAND_URL, length(args) >= 1 ? args[1] : nothing)
    mysql_com = fetch_header(MYSQL_COM_URL, length(args) >= 2 ? args[2] : nothing)
    field_types = fetch_header(FIELD_TYPES_URL, length(args) >= 3 ? args[3] : nothing)
    cmd_src = strip_comments(my_command)
    com_src = strip_comments(mysql_com)
    types_src = strip_comments(field_types)
    commands = filter(p -> !occursin(r"UNUSED|^COM_END$", p.first), parse_enum(cmd_src, "enum_server_command"))
    caps = parse_defines(com_src, r"^CLIENT_[A-Z0-9_]+$")
    push!(caps, "CLIENT_MULTI_FACTOR_AUTHENTICATION" => parse_defines(com_src, r"^MULTI_FACTOR_AUTHENTICATION$")[1].second)
    status = parse_enum(com_src, "SERVER_STATUS_flags_enum")
    types = parse_enum(types_src, "enum_field_types")
    # Column definition flags travel as int<2>; the server also defines internal-only flags
    # above 16 bits (UNIQUE_FLAG, BINCMP_FLAG, ...) that never appear on the wire.
    flags = filter(p -> p.second < (UInt64(1) << 16), parse_defines(com_src, r"^(?!CLIENT_)[A-Z_]+_FLAG$"))
    session = parse_enum(com_src, "enum_session_state_type")
    cursors = parse_enum(com_src, "enum_cursor_type")
    metadata = parse_enum(com_src, "enum_resultset_metadata")
    out = joinpath(@__DIR__, "..", "src", "Protocol", "constants_generated.jl")
    open(out, "w") do io
        println(io, "# GENERATED by scripts/gen_constants.jl — do not edit by hand.")
        println(io, "# Sources (numeric enum/define values only):")
        println(io, "#   ", MY_COMMAND_URL, " sha256=", bytes2hex(sha256(my_command)))
        println(io, "#   ", MYSQL_COM_URL, " sha256=", bytes2hex(sha256(mysql_com)))
        println(io, "#   ", FIELD_TYPES_URL, " sha256=", bytes2hex(sha256(field_types)))
        println(io)
        emit_group(io, "enum_server_command (my_command.h)", commands, "UInt8")
        emit_group(io, "capability flags (mysql_com.h); client-policy-only flags are kept separately in constants.jl", caps, "UInt64")
        emit_group(io, "SERVER_STATUS_flags_enum (mysql_com.h)", status, "UInt16")
        emit_group(io, "enum_field_types (field_types.h)", types, "UInt8")
        emit_group(io, "column definition flags (mysql_com.h)", flags, "UInt16")
        emit_group(io, "enum_session_state_type (mysql_com.h)", session, "UInt8")
        emit_group(io, "enum_cursor_type (mysql_com.h)", cursors, "UInt8")
        emit_group(io, "enum_resultset_metadata (mysql_com.h)", metadata, "UInt8")
        println(io, "const COMMAND_NAMES = Dict{UInt8, String}(")
        for (name, value) in commands
            println(io, "    UInt8(", value, ") => \"", name, "\",")
        end
        println(io, ")")
    end
    println("wrote ", normpath(out), ": ", length(commands), " commands, ", length(caps), " capability flags, ", length(status), " status flags, ", length(types), " field types, ", length(flags), " column flags")
    return nothing
end

main(ARGS)
