# `MySQL.load`: create a table from a Tables.jl source and insert its rows through one
# prepared statement inside a transaction.

const VALID_QUOTED_IDENTIFIER = r"^`(?:``|[^`])*`(?:\.`(?:``|[^`])*`)*$"

# Already-quoted identifiers pass through only when they are well formed (embedded backticks
# doubled); anything else is (re)quoted with `escape_identifier`.
function quoteid(str)
    name = String(str)
    wrapped = ncodeunits(name) >= 2 && first(name) == '`' && last(name) == '`'
    wrapped || return escape_identifier(name)
    occursin(VALID_QUOTED_IDENTIFIER, name) && return name
    return escape_identifier(chop(name; head=1, tail=1))
end
quoteid(::Connection, str) = quoteid(str)

sqltype(T) = get(SQLTYPES, nonmissingtype(T), "VARCHAR(255)")
sqltype(T, coltypes, name) = get(coltypes, name, sqltype(T))

const SQLTYPES = Dict{Type, String}(
    Int8 => "TINYINT",
    Int16 => "SMALLINT",
    Int32 => "INTEGER",
    Int64 => "BIGINT",
    UInt8 => "TINYINT UNSIGNED",
    UInt16 => "SMALLINT UNSIGNED",
    UInt32 => "INTEGER UNSIGNED",
    UInt64 => "BIGINT UNSIGNED",
    Float32 => "FLOAT",
    Float64 => "DOUBLE",
    DecFP.Dec64 => "NUMERIC(16, 6)",
    DecFP.Dec128 => "NUMERIC(35, 6)",
    Bool => "BOOL",
    Vector{UInt8} => "BLOB",
    String => "VARCHAR(255)",
    Date => "DATE",
    Time => "TIME",
    DateTime => "DATETIME",
    DateAndTime => "DATETIME(6)",
)

checkdupnames(names) = length(unique(map(x->lowercase(String(x)), names))) == length(names) || error("duplicate case-insensitive column names detected; mysql treats column names case insensitive")

function createtable(conn::Connection, nm::AbstractString, sch::Tables.Schema; debug::Bool=false, quoteidentifiers::Bool=true, createtableclause::AbstractString="CREATE TABLE", coltypes=Dict(), columnsuffix=Dict(), auto_increment_primary_key_name::Union{Nothing,AbstractString}=nothing)
    names = sch.names
    checkdupnames(names)
    types = [sqltype(T, coltypes, names[i]) for (i, T) in enumerate(sch.types)]
    columns = (string(quoteidentifiers ? quoteid(conn, String(names[i])) : names[i], ' ', types[i], ' ', get(columnsuffix, names[i], "")) for i = 1:length(names))
    auto_increment_column = if auto_increment_primary_key_name === nothing || isempty(auto_increment_primary_key_name)
        ""
    else
        primary_key_name = quoteidentifiers ? quoteid(conn, auto_increment_primary_key_name) : auto_increment_primary_key_name
        "$primary_key_name INT AUTO_INCREMENT PRIMARY KEY, "
    end
    debug && @info "executing create table statement: `$createtableclause $nm ($(auto_increment_column)$(join(columns, ", ")))`"
    return DBInterface.execute(conn, "$createtableclause $nm ($(auto_increment_column)$(join(columns, ", ")))")
end

"""
    MySQL.load(table, conn, name; append=true, quoteidentifiers=true, limit=typemax(Int64), createtableclause=nothing, coltypes=Dict(), columnsuffix=Dict(), debug=false)
    table |> MySQL.load(conn, name; append=true, quoteidentifiers=true, limit=typemax(Int64), createtableclause=nothing, coltypes=Dict(), columnsuffix=Dict(), debug=false)

Attempts to take a Tables.jl source `table` and load into the database represented by `conn` with table name `name`.

It first detects the `Tables.Schema` of the table source and generates a `CREATE TABLE` statement
with the appropriate column names and types. If no table name is provided, one will be autogenerated, like `mysql_xxxxx`.
The `CREATE TABLE` clause can be provided manually by passing the `createtableclause` keyword argument
(default `"CREATE TABLE IF NOT EXISTS"` with `append=true`, else `"CREATE TABLE"`), which
would allow specifying a temporary table.
Column types can be overridden by providing the `coltypes` keyword argument as a `Dict` of
column name (given as a `Symbol`) to a string of the SQL type. This allows, for example, using
a `LONGBLOB` instead of `BLOB` for large binary data by doing `coltypes=Dict(:Photo => "LONGBLOB")`.
Column definitions can also be enhanced by providing arguments to `columnsuffix` as a `Dict` of
column name (given as a `Symbol`) to a string of the enhancement that will come after name and type like
`[column name] [column type] enhancements`. This allows, for example, specifying the charset of a string column
by doing something like `columnsuffix=Dict(:Name => "CHARACTER SET utf8mb4")`.

`debug=true` logs the generated statements without row values; `debug=:values` also logs
each inserted row's values.

Do note that databases vary wildly in requirements for `CREATE TABLE` and column definitions
so it can be extremely difficult to load data generically. You may just need to tweak some of the provided
keyword arguments, but you may also need to execute the `CREATE TABLE` and `INSERT` statements
yourself. If you run into issues, you can [open an issue](https://github.com/JuliaDatabases/MySQL.jl/issues) and
we can see if there's something we can do to make it easier to use this function.
"""
function load end

load(conn::Connection, table::AbstractString="mysql_"*Random.randstring(5); kw...) = return x -> load(x, conn, table; kw...)

function load(itr, conn::Connection, name::AbstractString="mysql_" * Random.randstring(5); append::Bool=true, quoteidentifiers::Bool=true, debug::Union{Bool, Symbol}=false, limit::Integer=typemax(Int64), kw...)
    debug in (false, true, :values) || throw(ArgumentError("debug must be false, true, or :values"))
    isopen(conn) || throw(ArgumentError("`MySQL.Connection` is closed"))
    debug_statements = debug !== false
    debug_values = debug === :values
    # get data
    rows = Tables.rows(itr)
    sch = Tables.schema(rows)
    if sch === nothing
        # we want to ensure we always have a schema, so materialize if needed
        rows = Tables.rows(columntable(rows))
        sch = Tables.schema(rows)
    end
    # ensure table exists
    if quoteidentifiers
        name = quoteid(conn, name)
    end
    # Use IF NOT EXISTS when appending to avoid warnings on subsequent loads
    createclause = append ? "CREATE TABLE IF NOT EXISTS" : "CREATE TABLE"
    try
        createtable(conn, name, sch; quoteidentifiers=quoteidentifiers, debug=debug_statements, createtableclause=createclause, kw...)
    catch e
        @warn "error creating table" (e, catch_backtrace())
    end
    if !append
        debug_statements && @info "executing delete statement: `DELETE FROM $name`"
        DBInterface.execute(conn, "DELETE FROM $name")
    end
    # start a transaction for inserting rows
    DBInterface.transaction(conn) do
        params = chop(repeat("?,", length(sch.names)))
        columns = join((quoteid(conn, string(column)) for column in sch.names), ", ")
        insert = "INSERT INTO $name ($columns) VALUES ($params)"
        debug_statements && @info "executing insert statement: `$insert`"
        stmt = DBInterface.prepare(conn, insert)
        try
            for (i, row) in enumerate(rows)
                i > limit && break
                debug_values && @info "inserting row $i; $(Tables.Row(row))"
                DBInterface.execute(stmt, Tables.Row(row))
            end
        finally
            DBInterface.close!(stmt)
        end
    end

    return name
end
